### ISSUE TITLE
boards.txt contains incorrect information for Pro Micro 8Mhz

### ISSUE THREAD

**Issue by CircuitSerialKiller** [sparkfun/SF32u4_boards#16]
This line is missing:
promicro8.bootloader.tool=avrdude

efuse value is incorrect, the line should read:
promicro8.bootloader.extended_fuses=0xcb

Also, 8 second delay in 8MHz bootloader does not work in bootloader code when grounding rst 2x quickly.

**Comment by BrentWilkins** [comment]
Added a definition for the bootloader tool.  Thanks.

Unsure what is wrong with the extended fuses.  We have them set to detect brownout at 2.0V, rather than your suggested 2.6V.  Are we missing a case where this matters?  We are leaving bits 4:7 their default value of 1 (Table 28.3 in datasheet) but they aren't used anyway.

We found the 8 second delay on boot to be annoying, so we reduced it to around 1 second.  HIt reset sooner (immediately) on our boards.

**Comment by CircuitSerialKiller** [comment]
OK, yes the brown out detector value doesn't matter.
Grounding reset twice rapidly is supposed to keep it it in the bootloader for 8 seconds, which it does not (at least when using the 8MHz bootloader. It seems to keep it in the bootloader EXT_RESET_TIMEOUT_PERIOD seconds only, and without resetting twice rapidly, even less time. I started reviewing the bootloader code, but need more time as it's a lot to digest. 
I'll try recompiling and increasing
TIMEOUT_PERIOD
and 
EXT_RESET_TIMEOUT_PERIOD
